### ISSUE TITLE
unsigned addon

### ISSUE THREAD

**Issue by denniszl** [acourreges/livino-reader#1]
Firefox is giving me that the add-on can't be verified and I can't run it. It seems like in newer versions of Firefox, you cannot override add-ons to allow unverified add-ons to be run.

(I've set xpinstall.signatures.required to false to get by this in the past)

Any chance you could get this add on signed?

**Comment by acourreges** [comment]
Thanks for the report.

Here you go:
https://addons.mozilla.org/en-US/firefox/addon/livino-reader/
The add-on was signed by Mozilla and should be easy to install. 

Alternatively you can always use Firefox Developer Edition, it has a setting for installing unsigned add-ons.

I wanted to rewrite the code with the new WebExtension API (which Mozilla will require in the future) but unfortunately the file-system API is too limited and doesn't support local filesystem access yet... https://bugzilla.mozilla.org/show_bug.cgi?id=1246236
